sudo: false

language: php

cache:
  directories:
  - $HOME/.composer/cache
  - vendor

matrix:
  fast_finish: true
  include:
  - php: 5.5
  - php: 5.6
    env:
    - EXECUTE_DEPLOYMENT=true
  - php: 7
  - php: hhvm
  allow_failures:
  - php: hhvm

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - travis_retry composer install --no-interaction
  - composer info -i

script:
  - cd src/AppBundle/Resources/SocketIo && npm install && cd -
  - bin/phpunit -c app/

notifications:
  email: true
