hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login/connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

github_login:
    path: /login/check-github

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_webhook:
    resource: "@AppBundle/Controller/WebHookController.php"
    type:     annotation

app_notifications:
    resource: "@AppBundle/Controller/NotificationController.php"
    type:     annotation

app_home:
    resource: "@AppBundle/Controller/HomeController.php"
    type:     annotation
