# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    socket_url: "ws://127.0.0.1:%socket_port%"

services:
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }

    socket_admin_client:
        class: AppBundle\Ratchet\AdminClient
        arguments:
          - "%socket_url%"
          - "%socket_server_secret%"

    socket_user_client:
        class: Localhook\Localhook\Ratchet\UserClient
        arguments:
          - "%socket_url%"

#    socket_user_run_command:
#        class: Localhook\Localhook\Command\RunCommand
#        arguments: ["app:client:run"]
#        tags:
#          -  { name: console.command }