# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:

services:
    # Nullify this service. It is deprecated and raises an error on SensioLabs Insight
    twig.extension.actions:
        class: AppBundle\Twig\NullExtension
    socket_admin_client:
        class: AppBundle\Ratchet\AdminClient
        arguments:
          - "%socket_server_url%"

    socket_user_client:
        class: Localhook\Localhook\Ratchet\UserClient
        arguments:
          - "%socket_server_url%"

    app.registration_initialize_listener:
        class: AppBundle\UserBundle\EventListener\RegistrationInitializeListener
        tags:
            - { name: kernel.event_subscriber }

    request_simulator:
        class: AppBundle\RequestSimulator
        arguments:
          - "%notifications_prefix_url%"
          - "@router"
          - "@kernel"
          - "@request_stack"
